// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkm_provider_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pkm_5fprovider_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pkm_5fprovider_5fconfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pkm_5fprovider_5fconfig_2eproto;
namespace pkm {
class PKMProviderConfig;
struct PKMProviderConfigDefaultTypeInternal;
extern PKMProviderConfigDefaultTypeInternal _PKMProviderConfig_default_instance_;
}  // namespace pkm
PROTOBUF_NAMESPACE_OPEN
template<> ::pkm::PKMProviderConfig* Arena::CreateMaybeMessage<::pkm::PKMProviderConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pkm {

// ===================================================================

class PKMProviderConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pkm.PKMProviderConfig) */ {
 public:
  inline PKMProviderConfig() : PKMProviderConfig(nullptr) {}
  ~PKMProviderConfig() override;
  explicit PROTOBUF_CONSTEXPR PKMProviderConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PKMProviderConfig(const PKMProviderConfig& from);
  PKMProviderConfig(PKMProviderConfig&& from) noexcept
    : PKMProviderConfig() {
    *this = ::std::move(from);
  }

  inline PKMProviderConfig& operator=(const PKMProviderConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKMProviderConfig& operator=(PKMProviderConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PKMProviderConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const PKMProviderConfig* internal_default_instance() {
    return reinterpret_cast<const PKMProviderConfig*>(
               &_PKMProviderConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PKMProviderConfig& a, PKMProviderConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(PKMProviderConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKMProviderConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PKMProviderConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PKMProviderConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PKMProviderConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PKMProviderConfig& from) {
    PKMProviderConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PKMProviderConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pkm.PKMProviderConfig";
  }
  protected:
  explicit PKMProviderConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdkeyFileFieldNumber = 1,
    kIdkeyAuthTypeFieldNumber = 2,
    kIdkeyAuthFieldNumber = 3,
    kSrkAuthTypeFieldNumber = 4,
    kSrkAuthFieldNumber = 5,
  };
  // string idkey_file = 1;
  void clear_idkey_file();
  const std::string& idkey_file() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_idkey_file(ArgT0&& arg0, ArgT... args);
  std::string* mutable_idkey_file();
  PROTOBUF_NODISCARD std::string* release_idkey_file();
  void set_allocated_idkey_file(std::string* idkey_file);
  private:
  const std::string& _internal_idkey_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idkey_file(const std::string& value);
  std::string* _internal_mutable_idkey_file();
  public:

  // string idkey_auth_type = 2;
  void clear_idkey_auth_type();
  const std::string& idkey_auth_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_idkey_auth_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_idkey_auth_type();
  PROTOBUF_NODISCARD std::string* release_idkey_auth_type();
  void set_allocated_idkey_auth_type(std::string* idkey_auth_type);
  private:
  const std::string& _internal_idkey_auth_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idkey_auth_type(const std::string& value);
  std::string* _internal_mutable_idkey_auth_type();
  public:

  // string idkey_auth = 3;
  void clear_idkey_auth();
  const std::string& idkey_auth() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_idkey_auth(ArgT0&& arg0, ArgT... args);
  std::string* mutable_idkey_auth();
  PROTOBUF_NODISCARD std::string* release_idkey_auth();
  void set_allocated_idkey_auth(std::string* idkey_auth);
  private:
  const std::string& _internal_idkey_auth() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idkey_auth(const std::string& value);
  std::string* _internal_mutable_idkey_auth();
  public:

  // string srk_auth_type = 4;
  void clear_srk_auth_type();
  const std::string& srk_auth_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_srk_auth_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_srk_auth_type();
  PROTOBUF_NODISCARD std::string* release_srk_auth_type();
  void set_allocated_srk_auth_type(std::string* srk_auth_type);
  private:
  const std::string& _internal_srk_auth_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_srk_auth_type(const std::string& value);
  std::string* _internal_mutable_srk_auth_type();
  public:

  // string srk_auth = 5;
  void clear_srk_auth();
  const std::string& srk_auth() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_srk_auth(ArgT0&& arg0, ArgT... args);
  std::string* mutable_srk_auth();
  PROTOBUF_NODISCARD std::string* release_srk_auth();
  void set_allocated_srk_auth(std::string* srk_auth);
  private:
  const std::string& _internal_srk_auth() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_srk_auth(const std::string& value);
  std::string* _internal_mutable_srk_auth();
  public:

  // @@protoc_insertion_point(class_scope:pkm.PKMProviderConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_file_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_auth_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_auth_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr srk_auth_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr srk_auth_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pkm_5fprovider_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PKMProviderConfig

// string idkey_file = 1;
inline void PKMProviderConfig::clear_idkey_file() {
  _impl_.idkey_file_.ClearToEmpty();
}
inline const std::string& PKMProviderConfig::idkey_file() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_file)
  return _internal_idkey_file();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PKMProviderConfig::set_idkey_file(ArgT0&& arg0, ArgT... args) {
 
 _impl_.idkey_file_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_file)
}
inline std::string* PKMProviderConfig::mutable_idkey_file() {
  std::string* _s = _internal_mutable_idkey_file();
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_file)
  return _s;
}
inline const std::string& PKMProviderConfig::_internal_idkey_file() const {
  return _impl_.idkey_file_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_file(const std::string& value) {
  
  _impl_.idkey_file_.Set(value, GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_file() {
  
  return _impl_.idkey_file_.Mutable(GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::release_idkey_file() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_file)
  return _impl_.idkey_file_.Release();
}
inline void PKMProviderConfig::set_allocated_idkey_file(std::string* idkey_file) {
  if (idkey_file != nullptr) {
    
  } else {
    
  }
  _impl_.idkey_file_.SetAllocated(idkey_file, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.idkey_file_.IsDefault()) {
    _impl_.idkey_file_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_file)
}

// string idkey_auth_type = 2;
inline void PKMProviderConfig::clear_idkey_auth_type() {
  _impl_.idkey_auth_type_.ClearToEmpty();
}
inline const std::string& PKMProviderConfig::idkey_auth_type() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_auth_type)
  return _internal_idkey_auth_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PKMProviderConfig::set_idkey_auth_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.idkey_auth_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_auth_type)
}
inline std::string* PKMProviderConfig::mutable_idkey_auth_type() {
  std::string* _s = _internal_mutable_idkey_auth_type();
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_auth_type)
  return _s;
}
inline const std::string& PKMProviderConfig::_internal_idkey_auth_type() const {
  return _impl_.idkey_auth_type_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_auth_type(const std::string& value) {
  
  _impl_.idkey_auth_type_.Set(value, GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_auth_type() {
  
  return _impl_.idkey_auth_type_.Mutable(GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::release_idkey_auth_type() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_auth_type)
  return _impl_.idkey_auth_type_.Release();
}
inline void PKMProviderConfig::set_allocated_idkey_auth_type(std::string* idkey_auth_type) {
  if (idkey_auth_type != nullptr) {
    
  } else {
    
  }
  _impl_.idkey_auth_type_.SetAllocated(idkey_auth_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.idkey_auth_type_.IsDefault()) {
    _impl_.idkey_auth_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_auth_type)
}

// string idkey_auth = 3;
inline void PKMProviderConfig::clear_idkey_auth() {
  _impl_.idkey_auth_.ClearToEmpty();
}
inline const std::string& PKMProviderConfig::idkey_auth() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_auth)
  return _internal_idkey_auth();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PKMProviderConfig::set_idkey_auth(ArgT0&& arg0, ArgT... args) {
 
 _impl_.idkey_auth_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_auth)
}
inline std::string* PKMProviderConfig::mutable_idkey_auth() {
  std::string* _s = _internal_mutable_idkey_auth();
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_auth)
  return _s;
}
inline const std::string& PKMProviderConfig::_internal_idkey_auth() const {
  return _impl_.idkey_auth_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_auth(const std::string& value) {
  
  _impl_.idkey_auth_.Set(value, GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_auth() {
  
  return _impl_.idkey_auth_.Mutable(GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::release_idkey_auth() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_auth)
  return _impl_.idkey_auth_.Release();
}
inline void PKMProviderConfig::set_allocated_idkey_auth(std::string* idkey_auth) {
  if (idkey_auth != nullptr) {
    
  } else {
    
  }
  _impl_.idkey_auth_.SetAllocated(idkey_auth, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.idkey_auth_.IsDefault()) {
    _impl_.idkey_auth_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_auth)
}

// string srk_auth_type = 4;
inline void PKMProviderConfig::clear_srk_auth_type() {
  _impl_.srk_auth_type_.ClearToEmpty();
}
inline const std::string& PKMProviderConfig::srk_auth_type() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.srk_auth_type)
  return _internal_srk_auth_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PKMProviderConfig::set_srk_auth_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.srk_auth_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.srk_auth_type)
}
inline std::string* PKMProviderConfig::mutable_srk_auth_type() {
  std::string* _s = _internal_mutable_srk_auth_type();
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.srk_auth_type)
  return _s;
}
inline const std::string& PKMProviderConfig::_internal_srk_auth_type() const {
  return _impl_.srk_auth_type_.Get();
}
inline void PKMProviderConfig::_internal_set_srk_auth_type(const std::string& value) {
  
  _impl_.srk_auth_type_.Set(value, GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::_internal_mutable_srk_auth_type() {
  
  return _impl_.srk_auth_type_.Mutable(GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::release_srk_auth_type() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.srk_auth_type)
  return _impl_.srk_auth_type_.Release();
}
inline void PKMProviderConfig::set_allocated_srk_auth_type(std::string* srk_auth_type) {
  if (srk_auth_type != nullptr) {
    
  } else {
    
  }
  _impl_.srk_auth_type_.SetAllocated(srk_auth_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.srk_auth_type_.IsDefault()) {
    _impl_.srk_auth_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.srk_auth_type)
}

// string srk_auth = 5;
inline void PKMProviderConfig::clear_srk_auth() {
  _impl_.srk_auth_.ClearToEmpty();
}
inline const std::string& PKMProviderConfig::srk_auth() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.srk_auth)
  return _internal_srk_auth();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PKMProviderConfig::set_srk_auth(ArgT0&& arg0, ArgT... args) {
 
 _impl_.srk_auth_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.srk_auth)
}
inline std::string* PKMProviderConfig::mutable_srk_auth() {
  std::string* _s = _internal_mutable_srk_auth();
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.srk_auth)
  return _s;
}
inline const std::string& PKMProviderConfig::_internal_srk_auth() const {
  return _impl_.srk_auth_.Get();
}
inline void PKMProviderConfig::_internal_set_srk_auth(const std::string& value) {
  
  _impl_.srk_auth_.Set(value, GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::_internal_mutable_srk_auth() {
  
  return _impl_.srk_auth_.Mutable(GetArenaForAllocation());
}
inline std::string* PKMProviderConfig::release_srk_auth() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.srk_auth)
  return _impl_.srk_auth_.Release();
}
inline void PKMProviderConfig::set_allocated_srk_auth(std::string* srk_auth) {
  if (srk_auth != nullptr) {
    
  } else {
    
  }
  _impl_.srk_auth_.SetAllocated(srk_auth, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.srk_auth_.IsDefault()) {
    _impl_.srk_auth_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.srk_auth)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pkm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto
