// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkm_provider_config.proto

#include "pkm_provider_config.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace pkm {
class PKMProviderConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PKMProviderConfig> _instance;
} _PKMProviderConfig_default_instance_;
}  // namespace pkm
static void InitDefaultsscc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pkm::_PKMProviderConfig_default_instance_;
    new (ptr) ::pkm::PKMProviderConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pkm::PKMProviderConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_pkm_5fprovider_5fconfig_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_pkm_5fprovider_5fconfig_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_pkm_5fprovider_5fconfig_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_pkm_5fprovider_5fconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, idkey_file_),
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, idkey_auth_type_),
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, idkey_auth_),
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, srk_auth_type_),
  PROTOBUF_FIELD_OFFSET(::pkm::PKMProviderConfig, srk_auth_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::pkm::PKMProviderConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pkm::_PKMProviderConfig_default_instance_),
};

const char descriptor_table_protodef_pkm_5fprovider_5fconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031pkm_provider_config.proto\022\003pkm\"}\n\021PKMP"
  "roviderConfig\022\022\n\nidkey_file\030\001 \001(\t\022\027\n\017idk"
  "ey_auth_type\030\002 \001(\t\022\022\n\nidkey_auth\030\003 \001(\t\022\025"
  "\n\rsrk_auth_type\030\004 \001(\t\022\020\n\010srk_auth\030\005 \001(\tb"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_pkm_5fprovider_5fconfig_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_pkm_5fprovider_5fconfig_2eproto_sccs[1] = {
  &scc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_pkm_5fprovider_5fconfig_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pkm_5fprovider_5fconfig_2eproto = {
  false, false, descriptor_table_protodef_pkm_5fprovider_5fconfig_2eproto, "pkm_provider_config.proto", 167,
  &descriptor_table_pkm_5fprovider_5fconfig_2eproto_once, descriptor_table_pkm_5fprovider_5fconfig_2eproto_sccs, descriptor_table_pkm_5fprovider_5fconfig_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_pkm_5fprovider_5fconfig_2eproto::offsets,
  file_level_metadata_pkm_5fprovider_5fconfig_2eproto, 1, file_level_enum_descriptors_pkm_5fprovider_5fconfig_2eproto, file_level_service_descriptors_pkm_5fprovider_5fconfig_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_pkm_5fprovider_5fconfig_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_pkm_5fprovider_5fconfig_2eproto)), true);
namespace pkm {

// ===================================================================

void PKMProviderConfig::InitAsDefaultInstance() {
}
class PKMProviderConfig::_Internal {
 public:
};

PKMProviderConfig::PKMProviderConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:pkm.PKMProviderConfig)
}
PKMProviderConfig::PKMProviderConfig(const PKMProviderConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  idkey_file_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_idkey_file().empty()) {
    idkey_file_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_idkey_file(),
      GetArena());
  }
  idkey_auth_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_idkey_auth_type().empty()) {
    idkey_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_idkey_auth_type(),
      GetArena());
  }
  idkey_auth_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_idkey_auth().empty()) {
    idkey_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_idkey_auth(),
      GetArena());
  }
  srk_auth_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_srk_auth_type().empty()) {
    srk_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_srk_auth_type(),
      GetArena());
  }
  srk_auth_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_srk_auth().empty()) {
    srk_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_srk_auth(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:pkm.PKMProviderConfig)
}

void PKMProviderConfig::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto.base);
  idkey_file_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  idkey_auth_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  idkey_auth_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  srk_auth_type_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  srk_auth_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PKMProviderConfig::~PKMProviderConfig() {
  // @@protoc_insertion_point(destructor:pkm.PKMProviderConfig)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PKMProviderConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  idkey_file_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  idkey_auth_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  idkey_auth_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  srk_auth_type_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  srk_auth_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PKMProviderConfig::ArenaDtor(void* object) {
  PKMProviderConfig* _this = reinterpret_cast< PKMProviderConfig* >(object);
  (void)_this;
}
void PKMProviderConfig::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PKMProviderConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PKMProviderConfig& PKMProviderConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PKMProviderConfig_pkm_5fprovider_5fconfig_2eproto.base);
  return *internal_default_instance();
}


void PKMProviderConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:pkm.PKMProviderConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  idkey_file_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  idkey_auth_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  idkey_auth_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  srk_auth_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  srk_auth_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PKMProviderConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string idkey_file = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_idkey_file();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pkm.PKMProviderConfig.idkey_file"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string idkey_auth_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_idkey_auth_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pkm.PKMProviderConfig.idkey_auth_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string idkey_auth = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_idkey_auth();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pkm.PKMProviderConfig.idkey_auth"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string srk_auth_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_srk_auth_type();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pkm.PKMProviderConfig.srk_auth_type"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string srk_auth = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_srk_auth();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "pkm.PKMProviderConfig.srk_auth"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PKMProviderConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pkm.PKMProviderConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string idkey_file = 1;
  if (this->idkey_file().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_idkey_file().data(), static_cast<int>(this->_internal_idkey_file().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pkm.PKMProviderConfig.idkey_file");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_idkey_file(), target);
  }

  // string idkey_auth_type = 2;
  if (this->idkey_auth_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_idkey_auth_type().data(), static_cast<int>(this->_internal_idkey_auth_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pkm.PKMProviderConfig.idkey_auth_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_idkey_auth_type(), target);
  }

  // string idkey_auth = 3;
  if (this->idkey_auth().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_idkey_auth().data(), static_cast<int>(this->_internal_idkey_auth().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pkm.PKMProviderConfig.idkey_auth");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_idkey_auth(), target);
  }

  // string srk_auth_type = 4;
  if (this->srk_auth_type().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_srk_auth_type().data(), static_cast<int>(this->_internal_srk_auth_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pkm.PKMProviderConfig.srk_auth_type");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_srk_auth_type(), target);
  }

  // string srk_auth = 5;
  if (this->srk_auth().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_srk_auth().data(), static_cast<int>(this->_internal_srk_auth().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "pkm.PKMProviderConfig.srk_auth");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_srk_auth(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pkm.PKMProviderConfig)
  return target;
}

size_t PKMProviderConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pkm.PKMProviderConfig)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string idkey_file = 1;
  if (this->idkey_file().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_idkey_file());
  }

  // string idkey_auth_type = 2;
  if (this->idkey_auth_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_idkey_auth_type());
  }

  // string idkey_auth = 3;
  if (this->idkey_auth().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_idkey_auth());
  }

  // string srk_auth_type = 4;
  if (this->srk_auth_type().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_srk_auth_type());
  }

  // string srk_auth = 5;
  if (this->srk_auth().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_srk_auth());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PKMProviderConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pkm.PKMProviderConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const PKMProviderConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PKMProviderConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pkm.PKMProviderConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pkm.PKMProviderConfig)
    MergeFrom(*source);
  }
}

void PKMProviderConfig::MergeFrom(const PKMProviderConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pkm.PKMProviderConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.idkey_file().size() > 0) {
    _internal_set_idkey_file(from._internal_idkey_file());
  }
  if (from.idkey_auth_type().size() > 0) {
    _internal_set_idkey_auth_type(from._internal_idkey_auth_type());
  }
  if (from.idkey_auth().size() > 0) {
    _internal_set_idkey_auth(from._internal_idkey_auth());
  }
  if (from.srk_auth_type().size() > 0) {
    _internal_set_srk_auth_type(from._internal_srk_auth_type());
  }
  if (from.srk_auth().size() > 0) {
    _internal_set_srk_auth(from._internal_srk_auth());
  }
}

void PKMProviderConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pkm.PKMProviderConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PKMProviderConfig::CopyFrom(const PKMProviderConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pkm.PKMProviderConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PKMProviderConfig::IsInitialized() const {
  return true;
}

void PKMProviderConfig::InternalSwap(PKMProviderConfig* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  idkey_file_.Swap(&other->idkey_file_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  idkey_auth_type_.Swap(&other->idkey_auth_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  idkey_auth_.Swap(&other->idkey_auth_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  srk_auth_type_.Swap(&other->srk_auth_type_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  srk_auth_.Swap(&other->srk_auth_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PKMProviderConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pkm
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pkm::PKMProviderConfig* Arena::CreateMaybeMessage< ::pkm::PKMProviderConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::pkm::PKMProviderConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
