// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkm_provider_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pkm_5fprovider_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pkm_5fprovider_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pkm_5fprovider_5fconfig_2eproto;
namespace pkm {
class PKMProviderConfig;
class PKMProviderConfigDefaultTypeInternal;
extern PKMProviderConfigDefaultTypeInternal _PKMProviderConfig_default_instance_;
}  // namespace pkm
PROTOBUF_NAMESPACE_OPEN
template<> ::pkm::PKMProviderConfig* Arena::CreateMaybeMessage<::pkm::PKMProviderConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pkm {

// ===================================================================

class PKMProviderConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pkm.PKMProviderConfig) */ {
 public:
  inline PKMProviderConfig() : PKMProviderConfig(nullptr) {};
  virtual ~PKMProviderConfig();

  PKMProviderConfig(const PKMProviderConfig& from);
  PKMProviderConfig(PKMProviderConfig&& from) noexcept
    : PKMProviderConfig() {
    *this = ::std::move(from);
  }

  inline PKMProviderConfig& operator=(const PKMProviderConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline PKMProviderConfig& operator=(PKMProviderConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PKMProviderConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PKMProviderConfig* internal_default_instance() {
    return reinterpret_cast<const PKMProviderConfig*>(
               &_PKMProviderConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PKMProviderConfig& a, PKMProviderConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(PKMProviderConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PKMProviderConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PKMProviderConfig* New() const final {
    return CreateMaybeMessage<PKMProviderConfig>(nullptr);
  }

  PKMProviderConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PKMProviderConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PKMProviderConfig& from);
  void MergeFrom(const PKMProviderConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PKMProviderConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pkm.PKMProviderConfig";
  }
  protected:
  explicit PKMProviderConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pkm_5fprovider_5fconfig_2eproto);
    return ::descriptor_table_pkm_5fprovider_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdkeyFileFieldNumber = 1,
    kIdkeyAuthTypeFieldNumber = 2,
    kIdkeyAuthFieldNumber = 3,
    kSrkAuthTypeFieldNumber = 4,
    kSrkAuthFieldNumber = 5,
  };
  // string idkey_file = 1;
  void clear_idkey_file();
  const std::string& idkey_file() const;
  void set_idkey_file(const std::string& value);
  void set_idkey_file(std::string&& value);
  void set_idkey_file(const char* value);
  void set_idkey_file(const char* value, size_t size);
  std::string* mutable_idkey_file();
  std::string* release_idkey_file();
  void set_allocated_idkey_file(std::string* idkey_file);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_idkey_file();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_idkey_file(
      std::string* idkey_file);
  private:
  const std::string& _internal_idkey_file() const;
  void _internal_set_idkey_file(const std::string& value);
  std::string* _internal_mutable_idkey_file();
  public:

  // string idkey_auth_type = 2;
  void clear_idkey_auth_type();
  const std::string& idkey_auth_type() const;
  void set_idkey_auth_type(const std::string& value);
  void set_idkey_auth_type(std::string&& value);
  void set_idkey_auth_type(const char* value);
  void set_idkey_auth_type(const char* value, size_t size);
  std::string* mutable_idkey_auth_type();
  std::string* release_idkey_auth_type();
  void set_allocated_idkey_auth_type(std::string* idkey_auth_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_idkey_auth_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_idkey_auth_type(
      std::string* idkey_auth_type);
  private:
  const std::string& _internal_idkey_auth_type() const;
  void _internal_set_idkey_auth_type(const std::string& value);
  std::string* _internal_mutable_idkey_auth_type();
  public:

  // string idkey_auth = 3;
  void clear_idkey_auth();
  const std::string& idkey_auth() const;
  void set_idkey_auth(const std::string& value);
  void set_idkey_auth(std::string&& value);
  void set_idkey_auth(const char* value);
  void set_idkey_auth(const char* value, size_t size);
  std::string* mutable_idkey_auth();
  std::string* release_idkey_auth();
  void set_allocated_idkey_auth(std::string* idkey_auth);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_idkey_auth();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_idkey_auth(
      std::string* idkey_auth);
  private:
  const std::string& _internal_idkey_auth() const;
  void _internal_set_idkey_auth(const std::string& value);
  std::string* _internal_mutable_idkey_auth();
  public:

  // string srk_auth_type = 4;
  void clear_srk_auth_type();
  const std::string& srk_auth_type() const;
  void set_srk_auth_type(const std::string& value);
  void set_srk_auth_type(std::string&& value);
  void set_srk_auth_type(const char* value);
  void set_srk_auth_type(const char* value, size_t size);
  std::string* mutable_srk_auth_type();
  std::string* release_srk_auth_type();
  void set_allocated_srk_auth_type(std::string* srk_auth_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_srk_auth_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_srk_auth_type(
      std::string* srk_auth_type);
  private:
  const std::string& _internal_srk_auth_type() const;
  void _internal_set_srk_auth_type(const std::string& value);
  std::string* _internal_mutable_srk_auth_type();
  public:

  // string srk_auth = 5;
  void clear_srk_auth();
  const std::string& srk_auth() const;
  void set_srk_auth(const std::string& value);
  void set_srk_auth(std::string&& value);
  void set_srk_auth(const char* value);
  void set_srk_auth(const char* value, size_t size);
  std::string* mutable_srk_auth();
  std::string* release_srk_auth();
  void set_allocated_srk_auth(std::string* srk_auth);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_srk_auth();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_srk_auth(
      std::string* srk_auth);
  private:
  const std::string& _internal_srk_auth() const;
  void _internal_set_srk_auth(const std::string& value);
  std::string* _internal_mutable_srk_auth();
  public:

  // @@protoc_insertion_point(class_scope:pkm.PKMProviderConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_file_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_auth_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr idkey_auth_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr srk_auth_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr srk_auth_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_pkm_5fprovider_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PKMProviderConfig

// string idkey_file = 1;
inline void PKMProviderConfig::clear_idkey_file() {
  idkey_file_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PKMProviderConfig::idkey_file() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_file)
  return _internal_idkey_file();
}
inline void PKMProviderConfig::set_idkey_file(const std::string& value) {
  _internal_set_idkey_file(value);
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_file)
}
inline std::string* PKMProviderConfig::mutable_idkey_file() {
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_file)
  return _internal_mutable_idkey_file();
}
inline const std::string& PKMProviderConfig::_internal_idkey_file() const {
  return idkey_file_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_file(const std::string& value) {
  
  idkey_file_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PKMProviderConfig::set_idkey_file(std::string&& value) {
  
  idkey_file_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:pkm.PKMProviderConfig.idkey_file)
}
inline void PKMProviderConfig::set_idkey_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  idkey_file_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:pkm.PKMProviderConfig.idkey_file)
}
inline void PKMProviderConfig::set_idkey_file(const char* value,
    size_t size) {
  
  idkey_file_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:pkm.PKMProviderConfig.idkey_file)
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_file() {
  
  return idkey_file_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PKMProviderConfig::release_idkey_file() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_file)
  return idkey_file_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PKMProviderConfig::set_allocated_idkey_file(std::string* idkey_file) {
  if (idkey_file != nullptr) {
    
  } else {
    
  }
  idkey_file_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), idkey_file,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_file)
}
inline std::string* PKMProviderConfig::unsafe_arena_release_idkey_file() {
  // @@protoc_insertion_point(field_unsafe_arena_release:pkm.PKMProviderConfig.idkey_file)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return idkey_file_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PKMProviderConfig::unsafe_arena_set_allocated_idkey_file(
    std::string* idkey_file) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (idkey_file != nullptr) {
    
  } else {
    
  }
  idkey_file_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      idkey_file, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pkm.PKMProviderConfig.idkey_file)
}

// string idkey_auth_type = 2;
inline void PKMProviderConfig::clear_idkey_auth_type() {
  idkey_auth_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PKMProviderConfig::idkey_auth_type() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_auth_type)
  return _internal_idkey_auth_type();
}
inline void PKMProviderConfig::set_idkey_auth_type(const std::string& value) {
  _internal_set_idkey_auth_type(value);
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_auth_type)
}
inline std::string* PKMProviderConfig::mutable_idkey_auth_type() {
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_auth_type)
  return _internal_mutable_idkey_auth_type();
}
inline const std::string& PKMProviderConfig::_internal_idkey_auth_type() const {
  return idkey_auth_type_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_auth_type(const std::string& value) {
  
  idkey_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PKMProviderConfig::set_idkey_auth_type(std::string&& value) {
  
  idkey_auth_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:pkm.PKMProviderConfig.idkey_auth_type)
}
inline void PKMProviderConfig::set_idkey_auth_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  idkey_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:pkm.PKMProviderConfig.idkey_auth_type)
}
inline void PKMProviderConfig::set_idkey_auth_type(const char* value,
    size_t size) {
  
  idkey_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:pkm.PKMProviderConfig.idkey_auth_type)
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_auth_type() {
  
  return idkey_auth_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PKMProviderConfig::release_idkey_auth_type() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_auth_type)
  return idkey_auth_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PKMProviderConfig::set_allocated_idkey_auth_type(std::string* idkey_auth_type) {
  if (idkey_auth_type != nullptr) {
    
  } else {
    
  }
  idkey_auth_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), idkey_auth_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_auth_type)
}
inline std::string* PKMProviderConfig::unsafe_arena_release_idkey_auth_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:pkm.PKMProviderConfig.idkey_auth_type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return idkey_auth_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PKMProviderConfig::unsafe_arena_set_allocated_idkey_auth_type(
    std::string* idkey_auth_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (idkey_auth_type != nullptr) {
    
  } else {
    
  }
  idkey_auth_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      idkey_auth_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pkm.PKMProviderConfig.idkey_auth_type)
}

// string idkey_auth = 3;
inline void PKMProviderConfig::clear_idkey_auth() {
  idkey_auth_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PKMProviderConfig::idkey_auth() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.idkey_auth)
  return _internal_idkey_auth();
}
inline void PKMProviderConfig::set_idkey_auth(const std::string& value) {
  _internal_set_idkey_auth(value);
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.idkey_auth)
}
inline std::string* PKMProviderConfig::mutable_idkey_auth() {
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.idkey_auth)
  return _internal_mutable_idkey_auth();
}
inline const std::string& PKMProviderConfig::_internal_idkey_auth() const {
  return idkey_auth_.Get();
}
inline void PKMProviderConfig::_internal_set_idkey_auth(const std::string& value) {
  
  idkey_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PKMProviderConfig::set_idkey_auth(std::string&& value) {
  
  idkey_auth_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:pkm.PKMProviderConfig.idkey_auth)
}
inline void PKMProviderConfig::set_idkey_auth(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  idkey_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:pkm.PKMProviderConfig.idkey_auth)
}
inline void PKMProviderConfig::set_idkey_auth(const char* value,
    size_t size) {
  
  idkey_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:pkm.PKMProviderConfig.idkey_auth)
}
inline std::string* PKMProviderConfig::_internal_mutable_idkey_auth() {
  
  return idkey_auth_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PKMProviderConfig::release_idkey_auth() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.idkey_auth)
  return idkey_auth_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PKMProviderConfig::set_allocated_idkey_auth(std::string* idkey_auth) {
  if (idkey_auth != nullptr) {
    
  } else {
    
  }
  idkey_auth_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), idkey_auth,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.idkey_auth)
}
inline std::string* PKMProviderConfig::unsafe_arena_release_idkey_auth() {
  // @@protoc_insertion_point(field_unsafe_arena_release:pkm.PKMProviderConfig.idkey_auth)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return idkey_auth_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PKMProviderConfig::unsafe_arena_set_allocated_idkey_auth(
    std::string* idkey_auth) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (idkey_auth != nullptr) {
    
  } else {
    
  }
  idkey_auth_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      idkey_auth, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pkm.PKMProviderConfig.idkey_auth)
}

// string srk_auth_type = 4;
inline void PKMProviderConfig::clear_srk_auth_type() {
  srk_auth_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PKMProviderConfig::srk_auth_type() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.srk_auth_type)
  return _internal_srk_auth_type();
}
inline void PKMProviderConfig::set_srk_auth_type(const std::string& value) {
  _internal_set_srk_auth_type(value);
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.srk_auth_type)
}
inline std::string* PKMProviderConfig::mutable_srk_auth_type() {
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.srk_auth_type)
  return _internal_mutable_srk_auth_type();
}
inline const std::string& PKMProviderConfig::_internal_srk_auth_type() const {
  return srk_auth_type_.Get();
}
inline void PKMProviderConfig::_internal_set_srk_auth_type(const std::string& value) {
  
  srk_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PKMProviderConfig::set_srk_auth_type(std::string&& value) {
  
  srk_auth_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:pkm.PKMProviderConfig.srk_auth_type)
}
inline void PKMProviderConfig::set_srk_auth_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  srk_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:pkm.PKMProviderConfig.srk_auth_type)
}
inline void PKMProviderConfig::set_srk_auth_type(const char* value,
    size_t size) {
  
  srk_auth_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:pkm.PKMProviderConfig.srk_auth_type)
}
inline std::string* PKMProviderConfig::_internal_mutable_srk_auth_type() {
  
  return srk_auth_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PKMProviderConfig::release_srk_auth_type() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.srk_auth_type)
  return srk_auth_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PKMProviderConfig::set_allocated_srk_auth_type(std::string* srk_auth_type) {
  if (srk_auth_type != nullptr) {
    
  } else {
    
  }
  srk_auth_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), srk_auth_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.srk_auth_type)
}
inline std::string* PKMProviderConfig::unsafe_arena_release_srk_auth_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:pkm.PKMProviderConfig.srk_auth_type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return srk_auth_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PKMProviderConfig::unsafe_arena_set_allocated_srk_auth_type(
    std::string* srk_auth_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (srk_auth_type != nullptr) {
    
  } else {
    
  }
  srk_auth_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      srk_auth_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pkm.PKMProviderConfig.srk_auth_type)
}

// string srk_auth = 5;
inline void PKMProviderConfig::clear_srk_auth() {
  srk_auth_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PKMProviderConfig::srk_auth() const {
  // @@protoc_insertion_point(field_get:pkm.PKMProviderConfig.srk_auth)
  return _internal_srk_auth();
}
inline void PKMProviderConfig::set_srk_auth(const std::string& value) {
  _internal_set_srk_auth(value);
  // @@protoc_insertion_point(field_set:pkm.PKMProviderConfig.srk_auth)
}
inline std::string* PKMProviderConfig::mutable_srk_auth() {
  // @@protoc_insertion_point(field_mutable:pkm.PKMProviderConfig.srk_auth)
  return _internal_mutable_srk_auth();
}
inline const std::string& PKMProviderConfig::_internal_srk_auth() const {
  return srk_auth_.Get();
}
inline void PKMProviderConfig::_internal_set_srk_auth(const std::string& value) {
  
  srk_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PKMProviderConfig::set_srk_auth(std::string&& value) {
  
  srk_auth_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:pkm.PKMProviderConfig.srk_auth)
}
inline void PKMProviderConfig::set_srk_auth(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  srk_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:pkm.PKMProviderConfig.srk_auth)
}
inline void PKMProviderConfig::set_srk_auth(const char* value,
    size_t size) {
  
  srk_auth_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:pkm.PKMProviderConfig.srk_auth)
}
inline std::string* PKMProviderConfig::_internal_mutable_srk_auth() {
  
  return srk_auth_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PKMProviderConfig::release_srk_auth() {
  // @@protoc_insertion_point(field_release:pkm.PKMProviderConfig.srk_auth)
  return srk_auth_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PKMProviderConfig::set_allocated_srk_auth(std::string* srk_auth) {
  if (srk_auth != nullptr) {
    
  } else {
    
  }
  srk_auth_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), srk_auth,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:pkm.PKMProviderConfig.srk_auth)
}
inline std::string* PKMProviderConfig::unsafe_arena_release_srk_auth() {
  // @@protoc_insertion_point(field_unsafe_arena_release:pkm.PKMProviderConfig.srk_auth)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return srk_auth_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PKMProviderConfig::unsafe_arena_set_allocated_srk_auth(
    std::string* srk_auth) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (srk_auth != nullptr) {
    
  } else {
    
  }
  srk_auth_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      srk_auth, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pkm.PKMProviderConfig.srk_auth)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pkm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pkm_5fprovider_5fconfig_2eproto
