admin:
    access_log:
    -   name: envoy.access_loggers.file
        typed_config:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            log_format:
                json_format:
                    authority: '%REQ(:AUTHORITY)%'
                    bytes_received: '%BYTES_RECEIVED%'
                    bytes_sent: '%BYTES_SENT%'
                    duration: '%DURATION%'
                    method: '%REQ(:METHOD)%'
                    path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                    protocol: '%PROTOCOL%'
                    request_id: '%REQ(X-REQUEST-ID)%'
                    response_code: '%RESPONSE_CODE%'
                    response_flags: '%RESPONSE_FLAGS%'
                    start_time: '%START_TIME%'
                    upstream_host: '%UPSTREAM_HOST%'
                    upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
                    user_agent: '%REQ(USER-AGENT)%'
                    x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
            path: /home/ywen/envoy/admin.access_log.jsonl
    address:
        socket_address:
            address: 127.0.0.1
            port_value: 2223
dynamic_resources:
    cds_config:
        path: xDS/clusters.json
        resource_api_version: V3
    lds_config:
        path: xDS/listeners.json
        resource_api_version: V3
node:
    cluster: dc2333
    id: ywen-vm-22
